### ISSUE TITLE
关于代码中IoU和nIoU的计算问题

### ISSUE THREAD

**Issue by Drinkwaterever** [YimianDai/open-acm#14]
非常感谢您在红外小目标检测中的工作，我在仔细阅读您的代码后有一点小疑问，想向您请教。
在IoU和mIoU的指标计算中：
_, IoU = self.iou_metric.get()
_, nIoU = self.nIoU_metric.get()
return的值都是mIoU=IoU.mean(),请问一下这二者有什么区别？期望回复，谢谢

**Comment by YimianDai** [comment]
他们的差别在于 `batch_intersection_union` 这个函数的具体实现上，一个是 sample-wise 的累加，一个是整个 set 的累加。

您引用的 IoU 代码这里，IoU 只是个变量名，是一样的，没有区别。

IoU 和 nIoU 的区分，请查看两个文件的 `batch_intersection_union` 函数实现。
