### ISSUE TITLE
How to satisfy MXNet requirement for open-acm?

### ISSUE THREAD

**Issue by karacanil** [YimianDai/open-acm#16]
I'm using Jetson AGX Orin with Jetpack 5.1.2 and Cuda 11.4 and I'm unable to satisfy the MXNet requirement and run open-acm. MXNet is outdated and not maintained, thus building it with recent technology is not feasible. I've tried different branches of MXNet such as '1.x', '1.9.x' and '1.9.1' but no luck (can't configure for c++14). Has anyone encountered such an issue regarding the installation of open-acm. If anyone has successfully installed open-acm on this platform I'd like to know how.

**Comment by karacanil** [comment]
I was recently able to build mxnet version 1.9.1 from source by tracking down the issues caused by the c++11 vs c++14 contradiction and rewrite the parts that were throwing these errors.

**Comment by YimianDai** [comment]
I will update a PyTorch version in a few days.

**Comment by tan90du-sx** [comment]
期待您的更新！

**Comment by qianqian321** [comment]
> I will update a PyTorch version in a few days.

您好 ，请问您pytorch版本的更新了吗
