### ISSUE TITLE
测试数据问题请教

### ISSUE THREAD

**Issue by zmjjj** [YimianDai/open-acm#2]
作者您好，最近在准备一篇论文，想要与您所提出的这个方法进行对比。由于刚开始接受深度学习的红外小目标检测，所以对相关指示与框架运用的都不够熟练，因此想要请教您以下问题：

1. 该网络能够用您训练好的数据直接进行我手头数据集的测试呢，测试的部分即为mode='testval'这部分，不知道我理解是否正确；

2. 对数据集是否要进行预处理以满足此框架的需求，我看有一部分输入要求是.txt文件，而非.bmp和.png之类的图像文件；

3. 在此框架下测试其他数据集时，我该具体调整哪部分代码呢？

由于是深度学习小白，所以希望大佬能将以上问题进行回复，我很很感激您哒～

祝您论文高产且全是高水平论文！

**Comment by YimianDai** [comment]
1. 测试是 testval；
2. txt 里面的图像名称，根据路径 + 名称再去读取图像
3. 如果保持网络框架和 loss 不变，你只要改 Dataset 那边就行。但说实话，您最好还是再多了解些深度学习以及代码本身后再弄比较好，否则会变成我帮您写您的代码、调 bug 的了，这个已经超出了这个 github issues 的初衷和负责范围了，这个 repo 的 issues 只是个回答我论文和代码本身的平台。

祝您一切顺利！

过些天我会把更多的数据和代码放出来。SIRST 数据集的目的是 创建一个公共的 Benchmark，这样大家的方法能够有一个公平的平台比较。

**Comment by zmjjj** [comment]
好的 谢谢您！

**Comment by YimianDai** [comment]
没关系，不用客气，祝一切顺利！
