### ISSUE TITLE
关于测试问题

### ISSUE THREAD

**Issue by wangliyjs** [YimianDai/open-acm#3]
你好，您给出的训练代码已经跑起来了，但是只给出了IOU的结果，请问怎么在测试数据上进行可视化的显示呢？直观的看到检测结果

**Comment by YimianDai** [comment]
稍等下哈，我这篇论文没做可视化实验，但另一篇论文的代码做了可视化实验，目前也上传了可视化结果，但请您稍等些天哈，我这两周的事情又多又紧急。等空一下后我会放出来的（主要是我自己的 working repo 很大很杂、跟其他论文的代码依赖关系也很大，放出来的需要是一个独立的 repo，要多花一点时间整理，现在还没有心力弄，过两周就好了）

还请您理解和包容

**Comment by wangliyjs** [comment]
好的，谢谢回复

**Comment by YimianDai** [comment]
哈哈，没关系。我把这个 issue 又打开了，免得我忘记。

**Comment by YimianDai** [comment]
您好，我偷懒一下，测试代码请看我的另一个 repo。

https://github.com/YimianDai/open-alcnet/blob/master/visualize_local_contrast_networks.py
